name: Dan Wiggins
favicon: null
layout_spectrum: 0.011998276924714446
typography_spectrum: 0.4829095166642219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#4a4a4a'
    - '#8e8e8e'
    - '#aaaaaa'
  brandStrength: 0.5983061417937279
  lightness: 0.4299107033293694
  saturation: 0.2818518930580467
  rhythmicContrast: 0.7852948964573443
purpose: []
